# ACTIVIDAD 3.2

In [1]:
#Librerías necesarias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Carga de archivos y eliminación de las columnas no seleccionadas

In [30]:
data = pd.read_csv("Tokio.csv")
data2 = data.copy()
data2 = data2.drop(columns=["id", "listing_url", "scrape_id", "source", "picture_url", "host_id", "host_url", "host_name","host_since","host_about","host_thumbnail_url","host_picture_url","host_neighbourhood","host_listings_count","host_total_listings_count","neighbourhood_group_cleansed","calendar_last_scraped","first_review","review_scores_accuracy","license","calculated_host_listings_count","calculated_host_listings_count_entire_homes","calculated_host_listings_count_private_rooms","calculated_host_listings_count_shared_rooms"])
data2

,last_scraped,name,description,neighborhood_overview,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_verifications,...,number_of_reviews_l30d,last_review,review_scores_rating,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,reviews_per_month
0,2024-09-27,Oshiage Holiday Apartment,NaN,NaN,"Tokyo, Japan",within a day,100%,91%,t,"['email', 'phone']",...,1,2024-09-06,4.78,4.91,4.84,4.83,4.55,4.80,f,1.14
1,2024-09-27,Kero-kero house room 1,We have been in airbnb since 2011 and it has g...,We love Nishinippori because is nearer to Toky...,Japan,within an hour,100%,100%,t,"['email', 'phone']",...,2,2024-09-22,4.98,4.91,4.98,4.98,4.84,4.92,f,1.79
2,2024-09-27,4F Spacious Apartment in Shinjuku / Shibuya Tokyo,NEWLY RENOVATED property entirely for you & yo...,Hatagaya is a great neighborhood located 4 min...,"Tokyo, Japan",within an hour,100%,100%,t,"['email', 'phone']",...,3,2024-09-10,4.80,4.80,4.88,4.92,4.80,4.80,t,1.65
3,2024-09-27,5 mins Shibuya Cat modern sunny Shimokita,"Hi there, I am Wakana and I live with my two f...",The location is walkable distance to famous Sh...,"Tokyo, Japan",within a few hours,100%,100%,t,"['email', 'phone']",...,0,2024-06-26,4.95,4.84,4.94,4.98,4.92,4.90,f,1.92
4,2024-09-27,Stay with host Cozy private room Senju area,Ｓtay with host.We can help your travel.<br />B...,There are shopping mall near Senjuohashi stati...,"Tokyo, Japan",within an hour,100%,93%,t,"['email', 'phone']",...,2,2024-09-23,4.78,4.79,4.94,4.91,4.73,4.81,f,0.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18731,2024-09-27,高元寺站徒步4分钟,Relax in this unique and serene retreat.,NaN,"Suginami City, Japan",within an hour,100%,100%,f,"['email', 'phone']",...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,NaN
18732,2024-09-27,和绮新快乐居（独享三间房）,This one-of-a-kind home is unique in its own w...,NaN,"Tokyo, Japan",within an hour,100%,100%,f,['phone'],...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,NaN
18733,2024-09-27,G0305 位于新宿区中心位置，适合家庭和情侣；距離山手线高田马场站6分钟，交通便利，无电梯,Please relax with your family.<br />Narita Air...,NaN,"Tokyo, Japan",within an hour,100%,100%,f,"['email', 'phone']",...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,NaN
18734,2024-09-27,G0202 位于新宿区中心位置，适合家庭和情侣；距離山手线高田马场站6分钟，交通便利，无电梯,Please relax with your family.<br />Narita Air...,NaN,"Tokyo, Japan",within an hour,100%,100%,f,"['email', 'phone']",...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,NaN
18735,2024-09-27,池袋エリア/駅5分/新宿－渋谷ー銀座まで簡単25,★Newly renovated 1 bedroom house/sleeps up to ...,NaN,"Tokyo, Japan",within an hour,100%,100%,f,"['email', 'phone']",...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,NaN

In [31]:
#Convertir las columnas de tipo objeto que tenga valores numéricos a tipo numérico
#Primero se eliminan los caracteres especiales
data2["host_response_rate"] = data2["host_response_rate"].astype(str).str.replace('%', '')
data2["host_acceptance_rate"] = data2["host_acceptance_rate"].astype(str).str.replace('%', '')
#Se convierten a tipo numérico
data2["host_response_rate"] = pd.to_numeric(data2["host_response_rate"], errors='coerce')
data2["host_acceptance_rate"] = pd.to_numeric(data2["host_acceptance_rate"], errors='coerce')

In [32]:
#Verificamos información del dataset
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18736 entries, 0 to 18735
Data columns (total 51 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   last_scraped                 18736 non-null  object
 1   name                         18736 non-null  object
 2   description                  18371 non-null  object
 3   neighborhood_overview        11682 non-null  object
 4   host_location                13307 non-null  object
 5   host_response_time           18123 non-null  object
 6   host_response_rate           18123 non-null  float64
 7   host_acceptance_rate         18296 non-null  float64
 8   host_is_superhost            17320 non-null  object
 9   host_verifications           18736 non-null  object
 10  host_has_profile_pic         18736 non-null  object
 11  host_identity_verified       18736 non-null  object
 12  neighbourhood                11682 non-null  object
 13  neighbourhood_cleansed       18736 non-null  object
 14  latitude                     18736 non-null  float64
 15  longitude                    18736 non-null  float64
 16  property_type                18736 non-null  object
 17  room_type                    18736 non-null  object
 18  accommodates                 18736 non-null  int64
 19  bathrooms                    16912 non-null  float64
 20  bathrooms_text               18707 non-null  object
 21  bedrooms                     18454 non-null  float64
 22  beds                         16904 non-null  float64
 23  amenities                    18736 non-null  object
 24  price                        16904 non-null  object
 25  minimum_nights               18736 non-null  int64
 26  maximum_nights               18736 non-null  int64
 27  minimum_minimum_nights       18715 non-null  float64
 28  maximum_minimum_nights       18715 non-null  float64
 29  minimum_maximum_nights       18715 non-null  float64
 30  maximum_maximum_nights       18715 non-null  float64
 31  minimum_nights_avg_ntm       18715 non-null  float64
 32  maximum_nights_avg_ntm       18715 non-null  float64
 33  calendar_updated             0 non-null      float64
 34  has_availability             18632 non-null  object
 35  availability_30              18736 non-null  int64
 36  availability_60              18736 non-null  int64
 37  availability_90              18736 non-null  int64
 38  availability_365             18736 non-null  int64
 39  number_of_reviews            18736 non-null  int64
 40  number_of_reviews_ltm        18736 non-null  int64
 41  number_of_reviews_l30d       18736 non-null  int64
 42  last_review                  16331 non-null  object
 43  review_scores_rating         16331 non-null  float64
 44  review_scores_cleanliness    16330 non-null  float64
 45  review_scores_checkin        16330 non-null  float64
 46  review_scores_communication  16330 non-null  float64
 47  review_scores_location       16330 non-null  float64
 48  review_scores_value          16330 non-null  float64
 49  instant_bookable             18736 non-null  object
 50  reviews_per_month            16331 non-null  float64
dtypes: float64(21), int64(10), object(20)
memory usage: 7.3+ MB

## Identificar valores nullos

In [33]:
#Por columnas
valores_nulos = data2.isnull().sum()
valores_nulos

last_scraped                       0
name                               0
description                      365
neighborhood_overview           7054
host_location                   5429
host_response_time               613
host_response_rate               613
host_acceptance_rate             440
host_is_superhost               1416
host_verifications                 0
host_has_profile_pic               0
host_identity_verified             0
neighbourhood                   7054
neighbourhood_cleansed             0
latitude                           0
longitude                          0
property_type                      0
room_type                          0
accommodates                       0
bathrooms                       1824
bathrooms_text                    29
bedrooms                         282
beds                            1832
amenities                          0
price                           1832
minimum_nights                     0
maximum_nights                     0
minimum_minimum_nights            21
maximum_minimum_nights            21
minimum_maximum_nights            21
maximum_maximum_nights            21
minimum_nights_avg_ntm            21
maximum_nights_avg_ntm            21
calendar_updated               18736
has_availability                 104
availability_30                    0
availability_60                    0
availability_90                    0
availability_365                   0
number_of_reviews                  0
number_of_reviews_ltm              0
number_of_reviews_l30d             0
last_review                     2405
review_scores_rating            2405
review_scores_cleanliness       2406
review_scores_checkin           2406
review_scores_communication     2406
review_scores_location          2406
review_scores_value             2406
instant_bookable                   0
reviews_per_month               2405
dtype: int64

In [34]:
#Por dataset
valores_nulos = data.isnull().sum().sum()
valores_nulos

np.int64(108524)

## Sustitución de los valores nulos

In [35]:
#Sustituimos los valores nulos de las columnas de tipo object por ? debido a que no se puede 
# hacer una interpolación de los datos 
data2["last_scraped"] = data2["last_scraped"].fillna("?")
data2["name"] = data2["name"].fillna("?")
data2["price"] = data2["price"].fillna("?")
data2["description"] = data2["description"].fillna("?")
data2["neighborhood_overview"] = data2["neighborhood_overview"].fillna("?")
data2["host_location"] = data2["host_location"].fillna("?")
data2["host_response_time"] = data2["host_response_time"].fillna("?")
data2["host_is_superhost"] = data2["host_is_superhost"].fillna("?")
data2["host_verifications"] = data2["host_verifications"].fillna("?")
data2["host_has_profile_pic"] = data2["host_has_profile_pic"].fillna("?")
data2["host_identity_verified"] = data2["host_identity_verified"].fillna("?")
data2["neighbourhood"] = data2["neighbourhood"].fillna("?")
data2["neighbourhood_cleansed"] = data2["neighbourhood_cleansed"].fillna("?")
data2["property_type"] = data2["property_type"].fillna("?")
data2["room_type"] = data2["room_type"].fillna("?")
data2["bathrooms_text"] = data2["bathrooms_text"].fillna("?")
data2["amenities"] = data2["amenities"].fillna("?")
data2["has_availability"] = data2["has_availability"].fillna("?")
data2["last_review"] = data2["last_review"].fillna("?")
data2["instant_bookable"] = data2["instant_bookable"].fillna("?")

#Corroboramos que no haya valores nulos
valores_nulos = data2.isnull().sum()
valores_nulos

last_scraped                       0
name                               0
description                        0
neighborhood_overview              0
host_location                      0
host_response_time                 0
host_response_rate               613
host_acceptance_rate             440
host_is_superhost                  0
host_verifications                 0
host_has_profile_pic               0
host_identity_verified             0
neighbourhood                      0
neighbourhood_cleansed             0
latitude                           0
longitude                          0
property_type                      0
room_type                          0
accommodates                       0
bathrooms                       1824
bathrooms_text                     0
bedrooms                         282
beds                            1832
amenities                          0
price                              0
minimum_nights                     0
maximum_nights                     0
minimum_minimum_nights            21
maximum_minimum_nights            21
minimum_maximum_nights            21
maximum_maximum_nights            21
minimum_nights_avg_ntm            21
maximum_nights_avg_ntm            21
calendar_updated               18736
has_availability                   0
availability_30                    0
availability_60                    0
availability_90                    0
availability_365                   0
number_of_reviews                  0
number_of_reviews_ltm              0
number_of_reviews_l30d             0
last_review                        0
review_scores_rating            2405
review_scores_cleanliness       2406
review_scores_checkin           2406
review_scores_communication     2406
review_scores_location          2406
review_scores_value             2406
instant_bookable                   0
reviews_per_month               2405
dtype: int64

In [36]:
#Sustituimos los valores nulos de las columnas de tipo numérico por la mediana de los 
# valores en las variables percentuales
data2["host_response_rate"] = data2["host_response_rate"].fillna(data2["host_response_rate"].median())
data2["host_acceptance_rate"] = data2["host_acceptance_rate"].fillna(data2["host_acceptance_rate"].median())
#Corroboramos que no haya valores nulos
valores_nulos = data2.isnull().sum()
valores_nulos

last_scraped                       0
name                               0
description                        0
neighborhood_overview              0
host_location                      0
host_response_time                 0
host_response_rate                 0
host_acceptance_rate               0
host_is_superhost                  0
host_verifications                 0
host_has_profile_pic               0
host_identity_verified             0
neighbourhood                      0
neighbourhood_cleansed             0
latitude                           0
longitude                          0
property_type                      0
room_type                          0
accommodates                       0
bathrooms                       1824
bathrooms_text                     0
bedrooms                         282
beds                            1832
amenities                          0
price                              0
minimum_nights                     0
maximum_nights                     0
minimum_minimum_nights            21
maximum_minimum_nights            21
minimum_maximum_nights            21
maximum_maximum_nights            21
minimum_nights_avg_ntm            21
maximum_nights_avg_ntm            21
calendar_updated               18736
has_availability                   0
availability_30                    0
availability_60                    0
availability_90                    0
availability_365                   0
number_of_reviews                  0
number_of_reviews_ltm              0
number_of_reviews_l30d             0
last_review                        0
review_scores_rating            2405
review_scores_cleanliness       2406
review_scores_checkin           2406
review_scores_communication     2406
review_scores_location          2406
review_scores_value             2406
instant_bookable                   0
reviews_per_month               2405
dtype: int64

In [37]:
#Sustituimos la variable calendar_updated por un valor numérico concreto 0 debido a que la columna 
# esta llena de valores nulos
data2["calendar_updated"] = data2["calendar_updated"].fillna(0)
#Corroboramos que no haya valores nulos
valores_nulos = data2.isnull().sum()
valores_nulos

last_scraped                      0
name                              0
description                       0
neighborhood_overview             0
host_location                     0
host_response_time                0
host_response_rate                0
host_acceptance_rate              0
host_is_superhost                 0
host_verifications                0
host_has_profile_pic              0
host_identity_verified            0
neighbourhood                     0
neighbourhood_cleansed            0
latitude                          0
longitude                         0
property_type                     0
room_type                         0
accommodates                      0
bathrooms                      1824
bathrooms_text                    0
bedrooms                        282
beds                           1832
amenities                         0
price                             0
minimum_nights                    0
maximum_nights                    0
minimum_minimum_nights           21
maximum_minimum_nights           21
minimum_maximum_nights           21
maximum_maximum_nights           21
minimum_nights_avg_ntm           21
maximum_nights_avg_ntm           21
calendar_updated                  0
has_availability                  0
availability_30                   0
availability_60                   0
availability_90                   0
availability_365                  0
number_of_reviews                 0
number_of_reviews_ltm             0
number_of_reviews_l30d            0
last_review                       0
review_scores_rating           2405
review_scores_cleanliness      2406
review_scores_checkin          2406
review_scores_communication    2406
review_scores_location         2406
review_scores_value            2406
instant_bookable                  0
reviews_per_month              2405
dtype: int64

In [38]:
#Sustituimos las variables de review por la moda debido a que son variables categóricas
data2["review_scores_rating"] = data2["review_scores_rating"].fillna(data2["review_scores_rating"].mode()[0])
data2["review_scores_cleanliness"] = data2["review_scores_cleanliness"].fillna(data2["review_scores_cleanliness"].mode()[0])
data2["review_scores_checkin"] = data2["review_scores_checkin"].fillna(data2["review_scores_checkin"].mode()[0])
data2["review_scores_communication"] = data2["review_scores_communication"].fillna(data2["review_scores_communication"].mode()[0])
data2["review_scores_location"] = data2["review_scores_location"].fillna(data2["review_scores_location"].mode()[0])
data2["review_scores_value"] = data2["review_scores_value"].fillna(data2["review_scores_value"].mode()[0])
data2["reviews_per_month"] = data2["reviews_per_month"].fillna(data2["reviews_per_month"].mode()[0])
#Corroboramos que no haya valores nulos
valores_nulos = data2.isnull().sum()
valores_nulos

last_scraped                      0
name                              0
description                       0
neighborhood_overview             0
host_location                     0
host_response_time                0
host_response_rate                0
host_acceptance_rate              0
host_is_superhost                 0
host_verifications                0
host_has_profile_pic              0
host_identity_verified            0
neighbourhood                     0
neighbourhood_cleansed            0
latitude                          0
longitude                         0
property_type                     0
room_type                         0
accommodates                      0
bathrooms                      1824
bathrooms_text                    0
bedrooms                        282
beds                           1832
amenities                         0
price                             0
minimum_nights                    0
maximum_nights                    0
minimum_minimum_nights           21
maximum_minimum_nights           21
minimum_maximum_nights           21
maximum_maximum_nights           21
minimum_nights_avg_ntm           21
maximum_nights_avg_ntm           21
calendar_updated                  0
has_availability                  0
availability_30                   0
availability_60                   0
availability_90                   0
availability_365                  0
number_of_reviews                 0
number_of_reviews_ltm             0
number_of_reviews_l30d            0
last_review                       0
review_scores_rating              0
review_scores_cleanliness         0
review_scores_checkin             0
review_scores_communication       0
review_scores_location            0
review_scores_value               0
instant_bookable                  0
reviews_per_month                 0
dtype: int64

In [40]:
#En el resto de variables numéricas se sustituyen los valores nulos por promedio debido a que es la 
# mejor opción para no alterar los datos y poder hacer una interpretación correcta de los mismos
data2["bathrooms"] = data2["bathrooms"].fillna(data2["bathrooms"].mean())
data2["bedrooms"] = data2["bedrooms"].fillna(data2["bedrooms"].mean())
data2["beds"] = data2["beds"].fillna(data2["beds"].mean())
data2["minimum_minimum_nights"] = data2["minimum_minimum_nights"].fillna(data2["minimum_minimum_nights"].mean())
data2["maximum_minimum_nights"] = data2["maximum_minimum_nights"].fillna(data2["maximum_minimum_nights"].mean())
data2["minimum_maximum_nights"] = data2["minimum_maximum_nights"].fillna(data2["minimum_maximum_nights"].mean())
data2["maximum_maximum_nights"] = data2["maximum_maximum_nights"].fillna(data2["maximum_maximum_nights"].mean())
data2["minimum_nights_avg_ntm"] = data2["minimum_nights_avg_ntm"].fillna(data2["minimum_nights_avg_ntm"].mean())
data2["maximum_nights_avg_ntm"] = data2["maximum_nights_avg_ntm"].fillna(data2["maximum_nights_avg_ntm"].mean())
#Corroboramos que no haya valores nulos
valores_nulos = data2.isnull().sum()
valores_nulos

last_scraped                   0
name                           0
description                    0
neighborhood_overview          0
host_location                  0
host_response_time             0
host_response_rate             0
host_acceptance_rate           0
host_is_superhost              0
host_verifications             0
host_has_profile_pic           0
host_identity_verified         0
neighbourhood                  0
neighbourhood_cleansed         0
latitude                       0
longitude                      0
property_type                  0
room_type                      0
accommodates                   0
bathrooms                      0
bathrooms_text                 0
bedrooms                       0
beds                           0
amenities                      0
price                          0
minimum_nights                 0
maximum_nights                 0
minimum_minimum_nights         0
maximum_minimum_nights         0
minimum_maximum_nights         0
maximum_maximum_nights         0
minimum_nights_avg_ntm         0
maximum_nights_avg_ntm         0
calendar_updated               0
has_availability               0
availability_30                0
availability_60                0
availability_90                0
availability_365               0
number_of_reviews              0
number_of_reviews_ltm          0
number_of_reviews_l30d         0
last_review                    0
review_scores_rating           0
review_scores_cleanliness      0
review_scores_checkin          0
review_scores_communication    0
review_scores_location         0
review_scores_value            0
instant_bookable               0
reviews_per_month              0
dtype: int64

In [41]:
#Corroboramos que no haya valores nulos
valores_nulos = data2.isnull().sum().sum()
valores_nulos

np.int64(0)

## Generación de archivo CSV

In [42]:
#Guardamos el dataset sin valores nulos en un archivo csv
data2.to_csv("Tokio_sin_nulos.csv")